- name: Uninstall old versions
  apt:
    name: "{{item}}"
    state: absent
  with_items:
  - docker 
  - docker-engine 
  - docker.io

- name: Install prerequisites
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- name: lbs release
  shell: lsb_release -cs
  register: lsb_release
- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{lsb_release.stdout}} stable"

- name: Docker-CE
  apt:
    name: docker-ce
    update_cache: yes